apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
data:
  OPENAI_BASE_URL: {{ .Values.decisionLlm.baseUrl | quote }}
  OPENAI_MODEL: {{ .Values.decisionLlm.model | quote }}
  REM_MODEL: {{ .Values.remediationLlm.model | quote }}
  REM_BASE_URL: {{ .Values.remediationLlm.baseUrl | quote }}
  GEMINI_MODEL: {{ .Values.gemini.model | quote }}
  QUARKUS_PROFILE: {{ .Values.quarkusProfile | quote }}
