apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
